<?php
 $this->gradeArray[$i]['noOfCrates']=$temp['noOfCrates'];
                        $this->gradeStock[$this->gradeArray[$i]]['notedWeight']=$temp['notedWeight'];
                        $this->gradeStock[$this->gradeArray[$i]]['trueWeight']=$temp['trueWeight'];
                        $this->gradeStock[$this->gradeArray[$i]]['averageFruitCount']=$temp['averageFruitCount'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfSmallFruit']=$temp['sumOfSmallFruit'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfLargeFruit']=$temp['sumOfLargeFruit'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfFlyAttacked']=$temp['sumOfFlyAttacked'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfPeeledOff']=$temp['sumOfPeeledOff'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfBoreAttacked']=$temp['sumOfBoreAttacked'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfSandEmbedded']=$temp['sumOfSandEmbedded'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfShrivelled']=$temp['sumOfShrivelled'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfDeformed']=$temp['sumOfDeformed'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfVirusAttacked']=$temp['sumOfVirusAttacked'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfMechanicalDamaged']=$temp['sumOfMechanicalDamaged'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfYellowish']=$temp['sumOfYellowish'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfRustPatches']=$temp['sumOfRustPatches'];
                        $this->gradeStock[$this->gradeArray[$i]]['sumOfRotten']=$temp['sumOfRotten'];
                        $this->gradeStock[$this->gradeArray[$i]]['totalPerOfDefectGrade']=$temp['totalPerOfDefectGrade'];
                        $this->gradeStock[$this->gradeArray[$i]]['totalPerOfDefect']=$temp['totalPerOfDefect'];
                        $this->gradeStock[$this->gradeArray[$i]]['reducedPerOfDefectGrade']=$temp['reducedPerOfDefectGrade'];
                        $this->gradeStock[$this->gradeArray[$i]]['reducedPerOfDefect']=$temp['reducedPerOfDefect'];
                        $this->gradeStock[$this->gradeArray[$i]]['payableQuantity']=$temp['payableQuantity'];
                    