var map=[{"key":"-avgFruitCount","value":"averageFruitCount"},
			         {"key":"-slot-1-13","value":"fruitCount"},
			         {"key":"-sum-noCrates","value":"noOfCrates"},
			         
			         {"key":"-sum-notedWeight","value":"notedWeight"},
			         {"key":"-sum-pq-sum","value":"payableQuantity"},
			         {"key":"-sum-defects-reduced","value":"reducedPerOfDefect"},
			         {"key":"-sum-defectGrade-reduced","value":"reducedPerOfDefectGrade"},
			         {"key":"-sum-defects-sum","value":"totalPerOfDefect"},
			         {"key":"-sum-defectGrade-sum","value":"totalPerOfDefectGrade"},
			         {"key":"-sum-trueWeight","value":"trueWeight"},
			         //defects 
			         {"key":"-slot-2-13","value":"sumOfSmallFruit"},
			         {"key":"-slot-3-13","value":"sumOfLargeFruit"},
			         {"key":"-slot-4-13","value":"sumOfFlyAttacked"},
			         {"key":"-slot-5-13","value":"sumOfPeeledOff"},
			         {"key":"-slot-6-13","value":"sumOfBoreAttacked"},
			         {"key":"-slot-7-13","value":"sumOfSandEmbedded"},
			         {"key":"-slot-8-13","value":"sumOfShrivelled"},
			         {"key":"-slot-9-13","value":"sumOfDeformed"},
			         {"key":"-slot-10-13","value":"sumOfVirusAttacked"},
			         {"key":"-slot-11-13","value":"sumOfMechanicalDamaged"},
			         {"key":"-slot-12-13","value":"sumOfYellowish"},
			         {"key":"-slot-13-13","value":"sumOfRustPatches"},
			         {"key":"-slot-14-13","value":"sumOf45"},
			         {"key":"-slot-16-13","value":"sumOfRotten"}
				];
			var percentMap=[ 
			    		{"key":"-slot-2-14","value":"sumOfSmallFruit"},
			         {"key":"-slot-3-14","value":"sumOfLargeFruit"},
			         {"key":"-slot-4-14","value":"sumOfFlyAttacked"},
			         {"key":"-slot-5-14","value":"sumOfPeeledOff"},
			         {"key":"-slot-6-14","value":"sumOfBoreAttacked"},
			         {"key":"-slot-7-14","value":"sumOfSandEmbedded"},
			         {"key":"-slot-8-14","value":"sumOfShrivelled"},
			         {"key":"-slot-9-14","value":"sumOfDeformed"},
			         {"key":"-slot-10-14","value":"sumOfVirusAttacked"},
			         {"key":"-slot-11-14","value":"sumOfMechanicalDamaged"},
			         {"key":"-slot-12-14","value":"sumOfYellowish"},
			         {"key":"-slot-13-14","value":"sumOfRustPatches"},
			         {"key":"-slot-14-14","value":"sumOf45"},
			         {"key":"-slot-16-14","value":"sumOfRotten"}
				];
			var mapSamples=[ {"key":"-slot-0-","value":"centerId"},
			                 {"key":"-slot-1-","value":"fruitCount"},
			                 {"key":"-slot-2-","value":"smallFruit"},
			                 {"key":"-slot-3-","value":"largeFruit"},
			                 {"key":"-slot-4-","value":"flyAttacked"},
			                 {"key":"-slot-5-","value":"peeledOff"},
			                 {"key":"-slot-6-","value":"boreAttacked"},
			                 {"key":"-slot-7-","value":"sandEmbedded"},
			                 {"key":"-slot-8-","value":"shrivelled"},
			                 {"key":"-slot-9-","value":"deformed"},
			                 {"key":"-slot-10-","value":"virusAttacked"},
			                 {"key":"-slot-11-","value":"mechanicalDamaged"},
			                 {"key":"-slot-12-","value":"yellowish"},
			                 {"key":"-slot-13-","value":"rustPatches"},
			                 {"key":"-slot-14-","value":"fruits45"},
			                 {"key":"-slot-15-","value":"accepted"},
			                 {"key":"-slot-16-","value":"spoiled"},
				     			]

var errorGlobe={'status':false,'message':''};